openapi: 3.0.3
info:
  title: User API
  description: User API for user management
  version: 1.0.0
servers:
  - url: "http://{host}"
    description: The server for devloping in local computer
    variables:
      host:
        default: localhost
        enum:
          - localhost
          - www.ujun.com
paths:
  /api/users:
    post:
      description: Register new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                name:
                  type: string
            example:
              username: juntralala
              password: katasandi
              name: Ujun
      responses:
        201:
          description: Success register user
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        format: 32bit
                        default: 1
                      username:
                        type: string
                      name:
                        type: string
                  errors:
                    type: object
              example:
                data:
                  id: 1
                  username: juntralala
                  name: Ujun
                errors: {}
        400:
          description: Validation Error Response
          content:
            application/json:
              schema:
                type: object
              example:
                errors:
                  username:
                    - Username must not be blank
                    - Username min 6 character
                  password:
                    - Password must not be blank
                    - Password min 6 character

  /api/users/login:
    post:
      description: Login User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Success login user
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        format: 32bit
                        default: 1
                      username:
                        type: string
                      name:
                        type: string
                      token:
                        type: string
                  errors:
                    type: object
  /api/users/current:
    get:
      description: Get current user
      parameters:
        - name: Authorization
          in: header
          schema: 
            type: string
      responses:
        200:
          description: Success Get current user
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        format: 32bit
                        default: 1
                      username:
                        type: string
                      name:
                        type: string
                  errors:
                    type: object
    patch:
      description: Update current user
      parameters:
        - name: Authorization
          in: header
          schema: 
            type: string
      requestBody: 
        description: Update Current User
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Success update current user
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        format: 32bit
                        default: 1
                      username:
                        type: string
                      name:
                        type: string
                  errors:
                    type: object
  /api/users/logout: 
    delete:
      description: Logout current user
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
      responses:
        200: 
          description: Success logout current user
          content:
            application/json:
              schema:
                type: object
                properties:
                  data: 
                    type: boolean
                  errors:
                    type: object
